### ISSUE TITLE
newState deprecated - Use state instead

### ISSUE THREAD

**Issue by fu-zhou** [buanet/tutorials#1]
Hallo und vielen Dank für das tolle Script! ioBroker beschwert sich, dass newState durch state ersetzt werden soll, was ich auch mal probiert habe, dann läuft das Script aber nicht mehr...
![Unbenannt](https://user-images.githubusercontent.com/11984960/102946564-5166ca80-44c1-11eb-86f1-e9ec0079a4c9.png)
Hast du Lust das Script zu "ertüchtigen", so dass es weiterhin läuft und javascript trotzdem nichts zu meckern hat?

Danke vorab und Gruß!

**Comment by buanet** [comment]
This repository will be archived soon, so I am closing this issue. For more information, please refer to the repository’s README. Thank you!

Regards,
André
