### ISSUE TITLE
HTTP-URL für Snapshot ohne Funktion

### ISSUE THREAD

**Issue by railin** [buanet/tutorials#2]
Hallo, ich nutze das Skript seit geraumer Zeit zur Sendung eines Fotos von meiner Edimax-Kamera, wenn die Klingel betätigt wird.
Funktioniert super. Der Link für den Snapshot lautet: 

var cam_img = 'http://192.168.xxx.xxx:xxxx/snapshot.jpg?usr=xxxxx&pwd=xxxxx

Nutze ich eine Foscam-Kamera mit dem Link: var cam_img = 'http://192.168.xxx.xxx:xxx/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=xxx&pwd=xxx

auch alles Bestens.
Möchte jetzt eine Annke C800 einsetzen. Folgender Link erzeugt im Browser einen Snapshot:

http://192.168.xxx.xxx/ISAPI/Streaming/channels/1/picture als 
var cam_img = http://192.168.xxx.xxx/ISAPI/Streaming/channels/1/picture werden aber keine Bilder gespeichert.

Kann mir jemand auf die Sprünge helfen. Würde das Skript gerne weiter nutzen.
Vielen Dank für die Hilfe. Gruß, Rainer

**Comment by buanet** [comment]
This repository will be archived soon, so I am closing this issue. For more information, please refer to the repository’s README. Thank you!

Regards,
André
