### ISSUE TITLE
script-bilder-von-ueberwachungskamera-per-telegram in deinem Docker Container

### ISSUE THREAD

**Issue by mla4ger** [buanet/tutorials#3]
Hallo,

ich würde gerne auf deinen iobroker Docker Container umsteigen. Ich habe da versucht dein Skript mit umzusetzen, aber ohne Erfolg. Funktioniert das überhaupt im Docker Container?

Vielen Dank für deine Hilfe

**Comment by buanet** [comment]
This repository will be archived soon, so I am closing this issue. For more information, please refer to the repository’s README. Thank you!

Regards,
André
