### ISSUE TITLE
Verwendete funktion "request" abgekündigt

### ISSUE THREAD

**Issue by lcd4linux** [buanet/tutorials#4]
Bei der Ausführung des Scripts kommt es zu einer Fehlermeldung.
`request package is deprecated - please use httpGet (or a stable lib like axios) instead!`

ich habe bereits versucht das Script auf die empfohlene Funktion "httpget" zu ändern aber ohne Erfolg.

**Comment by buanet** [comment]
This repository will be archived soon, so I am closing this issue. For more information, please refer to the repository’s README. Thank you!

Regards,
André
